### ISSUE TITLE
Report todo

### ISSUE THREAD

**Issue by Ca-moes** [FEUP-ESOF-2020-21/open-cx-t4g1-grupo-1#33]
- [x] Domain Model - Um UML com classes de nivel mais alto e mostrar como interagem entre si. Podemos usar [isto](https://stackoverflow.com/questions/62600093/how-to-generate-a-class-diagram-in-dart) para criar automaticamente o diagrama

---

- [x] Architecture and Design - Descrição breve sobre os componentes do projeto e as interações entre si
- [x] Logical architecture - Mostrar classes UML e um textinho com os diretórios e como se relacionam entre si. Objetivo é mostrar uma estrutura lógica de alto nivel, referenciado "packages". Exemplo:
![image](https://user-images.githubusercontent.com/54408098/100450858-454c4080-30ae-11eb-9470-d8ba8232b4fb.png)

   - [x] horizontal decomposition - Tal como em LPOO havia Model-View-Controller, na decomposição horizontal define-se camadas oara separar a UI, lógica do programa, base de dados, etc..
   - [x] vertical decomposition - Define uma hierarquia de subsystemas que cobrem todas as camadas de cima, por exemplo, criar uma talk tem um ecrâ (UI), só deixa submeter se todos os campos estiverem preenchidos (lógica) e modifica a base de dados.
- [x] Physical architecture - UML como o de baixo para mostrar a estrutura física do nosso projeto. Necessário descrever as tecnologias usadas
![image](https://user-images.githubusercontent.com/54408098/100450634-ee466b80-30ad-11eb-9ceb-a869aeef2c83.png)

- [x] Prototype - Descrever com detalhe as user stories implementadas e como foram implementadas

---

- [x] Implementation - Mostrar como foram implementadas coisas mais complicadas, com links para o código. A secção tem de ser curta e tem como objetivo esclarecer e ajudar pessoas que veêm o código pela primeira vez

---

- [x] Test
   - [x] test plan - Descrever features que foram testadas e como foram testadas. Flutter já tem uma ferramenta de teste
   - [x] test case specifications - Especificar alguns testes feitos

---

- [x] Configuration and change management - Como Foi o **manage** do projeto: usamos PR e feature branches para tratar de diferentes issues.

---

- [x] Project management - Adotamos GitHubProjects, com um backlog de todas as user stories a implementar e um secção todo que era atualizada no inicio de cada iteração com os objetivos para aquelas 2 semanas
